server:
  port: 8088

logging:
  level:
    org.springframework: debug


spring:
  # security
  security:
    user:
      name: ggyool
      password: password
  # 다국어 파일의 이름 messages.properties
  messages:
    basename: messages
  # jpa
  datasource:
    url: jdbc:h2:mem:tempdb
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

# h2
h2:
  console:
    enabled: true


# actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"

